---
- name: Configure fail2ban
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: '0644'
  notify: restart fail2ban

- name: Ensure fail2ban is running
  systemd:
    name: fail2ban
    state: started
    enabled: yes