---
- name: Install UFW firewall
  apt:
    name: ufw
    state: present

- name: Configure UFW defaults
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }

- name: Allow SSH access
  ufw:
    rule: allow
    name: OpenSSH
    src: "{{ item }}"
  loop: "{{ allowed_ssh_ips }}"

- name: Allow HTTP and HTTPS
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - '80'
    - '443'
    
- name: Enable UFW
  ufw:
    state: enabled

- name: Check UFW status
  command: ufw status verbose
  register: ufw_status
  changed_when: false

- name: Display firewall status
  debug:
    msg: "{{ ufw_status.stdout_lines }}"